apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: better-uptime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: betterptimeacr.azurecr.io/uptime-primary-frontend:uptime-primary-26032026-v1.0.4d15
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 750Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
      imagePullSecrets:
        - name: imagepullsecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: better-uptime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: betterptimeacr.azurecr.io/uptime-primary-backend:uptime-primary-26032026-v1.0.837f
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 150m
              memory: 500Mi
            limits:
              cpu: 250m
              memory: 750Mi
          readinessProbe:
            httpGet:
              path: /api/health
              port: 80
      imagePullSecrets:
        - name: imagepullsecret
